trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
- script: |
    curl -sSL https://install.python-poetry.org | python
    echo "##vso[task.prependpath]$HOME/.local/bin"
    poetry install
  displayName: 'Install everything'
- script: |
    poetry run pytest --cov=codecov_test
  displayName: 'Run tests'
- script: |
    curl --retry 3 -o codecov https://uploader.codecov.io/latest/linux/codecov
    chmod +x codecov
    poetry run coverage xml
    ./codecov
  displayName: 'upload coverage'
